;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	))

(setq mc/cmds-to-run-once
      '(
	mark-word-or-next-word-like-this
	swiper
	))
